[workspace]
members = [
    "tarantool",
    "tarantool-proc",
    "tlua",
    "tlua-derive",
    "tests",
    "examples/demo",
    "examples/easy",
    "examples/harder",
    "examples/hardest",
    "examples/read",
    "examples/write",
    "examples/cluster_node"
]

