[package]
name = "fiber-select"
version = "0.1.0"
edition = "2021"
license = "BSD-2-Clause"

[dependencies]
serde = "1.0"

[dependencies.tarantool]
path = "../../tarantool"

[lib]
test = false
crate-type = ["cdylib"]
