[package]
name = "perf-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tarantool = { path = "../tarantool", features = ["picodata"] }

[lib]
crate-type = ["cdylib"]
